### PR TITLE
Added ascii art to readme

### PR DESCRIPTION
**Pull request by eugeneyche**

### CODE REVIEW

**Comment by eugeneyche** [comment]
Meh, this doesn't look as good as I had hoped, will update :sob:

**Comment by jytang** [comment]
Is [this](https://github.com/addtea/dragonslave/blob/022b8c2d6d4358948ef4298c6baf32d9fc7df517/README.md) any better?
Also, really appropriate quote :fire:

**Comment by eugeneyche** [comment]
Holy cow, yes!

:ship: it

**Comment by eugeneyche** [comment]
I changed to quote to italics, so it's less busy 👍.

BTW this lgtm, so I'm going to go ahead and merge it in. 🎉

**Pull request merged**
